/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/Shared/ActionButton.vue')['default']
    CollapsibleAccordion: typeof import('./src/components/Shared/CollapsibleAccordion.vue')['default']
    ContactForm: typeof import('./src/components/Shared/ContactForm.vue')['default']
    CustomInput: typeof import('./src/components/JobSearch/CustomInput.vue')['default']
    HeaderContainer: typeof import('./src/components/Shared/HeaderContainer.vue')['default']
    JobFilters: typeof import('./src/components/JobResults/JobFilters.vue')['default']
    JobFiltersGroup: typeof import('./src/components/JobResults/JobFiltersGroup.vue')['default']
    JobListing: typeof import('./src/components/JobResults/JobListing.vue')['default']
    JobListings: typeof import('./src/components/JobResults/JobListings.vue')['default']
    JobSearchForm: typeof import('./src/components/JobSearch/JobSearchForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotLight: typeof import('./src/components/JobSearch/SpotLight.vue')['default']
    TheHeadline: typeof import('./src/components/JobSearch/TheHeadline.vue')['default']
    TheMainNav: typeof import('./src/components/Navigation/TheMainNav.vue')['default']
    TheSubnav: typeof import('./src/components/Navigation/TheSubnav.vue')['default']
  }
}
